version: '3'

services:
    mongodb:
        image: mongo:4.4
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: ecommerce-db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    app:
        build:
            context: .
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
        env_file:
            - .env
